#
services:
  - docker
  
jobs:
  include:
   - stage: building images
     name: building amd64 image
     arch: amd64
     script:
       - docker build --rm -t "quay.io/bivasda2/che-machine-exec:${TRAVIS_COMMIT}-amd64" -f build/dockerfiles/Dockerfile 
