services:
  - docker
  
jobs:
  include:
   - stage: building images
     name: building amd64 image
     arch: amd64
     script:
       - if [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-99]+\.[0-99]+$ ]]; then --no-git-tag-version "${TRAVIS_TAG}"; fi
       - docker build --rm -t "quay.io/bivasda2/che-machine-exec:${TRAVIS_COMMIT}-amd64" -f build/dockerfiles/Dockerfile 
